### ISSUE TITLE
SyntaxError: Unexpected token > 

### ISSUE THREAD

**Issue by R0uter** [UnsignedInt8/LightSword#5]
```
root@iZ28qmuv9zaZ:~# lsbridge -s 000.92.41.108 -p 40020 -l 40020

/usr/local/lib/node_modules/lightsword/build/bridge/bin/cli.js:35
    ipc.sendCommand('bridge', args.daemon, (code) => process.exit(code));
                                                   ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by UnsignedInt8** [comment]
应该不会出现这个错误的啊。。。

你用的却是是Node 4.0以上版本吧？

**Comment by R0uter** [comment]
nodejs 0.10.25
?

**Comment by UnsignedInt8** [comment]
必须要node 4.0以上版本的，你可以安装 n ，这是一个node版本管理器，然后用 n 安装最新版的node

```
> npm i -g n

> sudo n stable
```

**Comment by R0uter** [comment]
wget -qO- https://deb.nodesource.com/setup_5.x | sudo bash -

我使用这个更新了源然后才成功安装，你的方法不行，下载不下来，估计是锅内屏蔽了………………

**Comment by UnsignedInt8** [comment]
去官网下载源码包编译

**Comment by R0uter** [comment]
换了官网提供的源，已经安装成功：）

`wget -qO- https://deb.nodesource.com/setup_5.x | sudo bash -`

**Comment by UnsignedInt8** [comment]
Congratulations!
